name: dsai
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py311hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - pyzmq=27.1.0=py311hcf8288c_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.11.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - ascii-colors==0.11.4
      - asgiref==3.10.0
      - attrs==25.4.0
      - babel==2.17.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.2
      - bitsandbytes==0.48.2
      - bleach==6.3.0
      - blinker==1.9.0
      - boto3==1.40.74
      - botocore==1.40.74
      - brotli==1.2.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - configparser==7.2.0
      - contourpy==1.3.3
      - courlan==1.3.2
      - cryptography==46.0.3
      - cssselect2==0.8.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - dateparser==1.2.2
      - defusedxml==0.7.1
      - dill==0.4.0
      - distro==1.9.0
      - django==5.2.8
      - docker==7.1.0
      - doclayout-yolo==0.0.4
      - docstring-parser==0.17.0
      - einops==0.8.1
      - fast-langdetect==0.2.5
      - fastapi==0.121.2
      - fasttext-predict==0.9.2.4
      - ffmpy==1.0.0
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.1
      - google-auth-oauthlib==1.2.3
      - google-cloud-aiplatform==1.127.0
      - google-cloud-bigquery==3.38.0
      - google-cloud-core==2.5.0
      - google-cloud-resource-manager==1.15.0
      - google-cloud-storage==3.5.0
      - google-crc32c==1.7.1
      - google-genai==1.50.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.72.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - gradio-pdf==0.0.22
      - greenlet==3.2.4
      - groovy==0.1.2
      - grpc-google-iam-v1==0.14.3
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - htmldate==1.9.4
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-retries==0.4.5
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - joblib==1.5.2
      - json-repair==0.53.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - justext==3.0.2
      - kaggle==1.7.4.5
      - kiwisolver==1.4.9
      - langchain==1.0.7
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.5
      - langchain-ollama==1.0.0
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.4
      - langgraph-sdk==0.2.9
      - langsmith==0.4.43
      - lazy-loader==0.4
      - lightning-sdk==2025.11.13.post0
      - lightrag-hku==1.4.9.8
      - litai==0.0.10
      - loguru==0.7.3
      - lxml==6.0.2
      - lxml-html-clean==0.4.3
      - magika==0.6.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mcp==1.21.1
      - mdurl==0.1.2
      - mineru==2.6.4
      - mineru-vl-utils==0.1.15
      - modelscope==1.31.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - mysqlclient==2.2.7
      - nano-vectordb==0.0.4.3
      - narwhals==2.11.0
      - networkx==3.5
      - numpy==2.3.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - ollama==0.6.1
      - omegaconf==2.3.0
      - onnxruntime==1.23.2
      - openai==2.8.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - pandas==2.3.3
      - pdfminer-six==20250506
      - pdftext==0.6.3
      - pillow==12.0.0
      - pip==25.3
      - pipmaster==1.0.10
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyclipper==1.3.0.post6
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pydub==0.25.1
      - pydyf==0.11.0
      - pyjwt==2.10.1
      - pyparsing==3.2.5
      - pypdf==6.3.0
      - pypdfium2==4.30.0
      - pyphen==0.17.2
      - pypinyin==0.55.0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - raganything==1.2.8
      - referencing==0.37.0
      - regex==2025.11.3
      - reportlab==4.4.4
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - robust-downloader==0.0.2
      - rpds-py==0.28.0
      - rsa==4.9.1
      - ruff==0.14.5
      - s3transfer==0.14.0
      - safehttpx==0.1.7
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - shapely==2.1.2
      - shellingham==1.5.4
      - simple-term-menu==1.6.6
      - simsimd==6.5.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - sse-starlette==3.0.3
      - sseclient-py==1.8.0
      - starlette==0.49.3
      - streamlit==1.51.0
      - stringzilla==4.2.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - text-unidecode==1.3
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tiktoken==0.12.0
      - timm==1.0.22
      - tinycss2==1.4.0
      - tinyhtml5==2.0.0
      - tld==0.13.1
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - trafilatura==2.0.0
      - transformers==4.57.1
      - triton==3.3.1
      - typer==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - ultralytics==8.3.228
      - ultralytics-thop==2.0.18
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vertexai==1.43.0
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - weasyprint==66.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - wget==3.2
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - yarl==1.22.0
      - youtube-transcript-api==1.2.3
      - yt-dlp==2025.11.12
      - zopfli==0.4.0
      - zstandard==0.25.0
prefix: /home/ubuntu/miniconda3/envs/dsai
